require_relative '../lib/version'
require_relative '../lib/shipmodule'
require_relative '../lib/cli'
require_relative '../lib/module'
require_relative '../lib/ship'
require_relative '../lib/manufacturer'
require_relative '../lib/scraper'


require 'uri'
require 'colorize'
require 'pry'
require 'net/http'
require 'json'
require 'open-uri'
require 'nokogiri'
