# require 'bundler'
# Bundler.require
require 'require_all'
require_all './lib'

# require_relative '../lib/version'
# require_relative '../lib/shipmodule'
# require_relative '../lib/engimodule'
# require_relative '../lib/cli'
# require_relative '../lib/module'
# require_relative '../lib/ship'
# require_relative '../lib/manufacturer'
# require_relative '../lib/engineer'
# require_relative '../lib/component'
# require_relative '../lib/scraper'

# require 'pry'
require 'uri'
require 'colorize'
require 'net/http'
require 'json'
require 'open-uri'
require 'nokogiri'
